spring.datasource.url=jdbc:h2:mem:polaflix
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

server.port=8081
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jackson.mapper.default-view-inclusion=false

springdoc.api-docs.path=/swagger-json
